project_id = "cpxjhyxzleomwgpyvkun"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.create-demo-user]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = false
  [functions.seed-demo-dreams]
    verify_jwt = false
